// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raker.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WorkerJobStatus int32

const (
	WorkerJobStatus_NOT_STARTED WorkerJobStatus = 0
	WorkerJobStatus_IN_PROGRESS WorkerJobStatus = 1
)

var WorkerJobStatus_name = map[int32]string{
	0: "NOT_STARTED",
	1: "IN_PROGRESS",
}

var WorkerJobStatus_value = map[string]int32{
	"NOT_STARTED": 0,
	"IN_PROGRESS": 1,
}

func (x WorkerJobStatus) String() string {
	return proto.EnumName(WorkerJobStatus_name, int32(x))
}

func (WorkerJobStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_97affea0cdd5c5fb, []int{0}
}

type Task struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_97affea0cdd5c5fb, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type WorkerJob struct {
	Version              int32                `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Task                 *Task                `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Status               WorkerJobStatus      `protobuf:"varint,3,opt,name=status,proto3,enum=proto.WorkerJobStatus" json:"status,omitempty"`
	Period               *duration.Duration   `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	Prev                 *timestamp.Timestamp `protobuf:"bytes,5,opt,name=prev,proto3" json:"prev,omitempty"`
	Next                 *timestamp.Timestamp `protobuf:"bytes,6,opt,name=next,proto3" json:"next,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *WorkerJob) Reset()         { *m = WorkerJob{} }
func (m *WorkerJob) String() string { return proto.CompactTextString(m) }
func (*WorkerJob) ProtoMessage()    {}
func (*WorkerJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_97affea0cdd5c5fb, []int{1}
}

func (m *WorkerJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerJob.Unmarshal(m, b)
}
func (m *WorkerJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerJob.Marshal(b, m, deterministic)
}
func (m *WorkerJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerJob.Merge(m, src)
}
func (m *WorkerJob) XXX_Size() int {
	return xxx_messageInfo_WorkerJob.Size(m)
}
func (m *WorkerJob) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerJob.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerJob proto.InternalMessageInfo

func (m *WorkerJob) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *WorkerJob) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *WorkerJob) GetStatus() WorkerJobStatus {
	if m != nil {
		return m.Status
	}
	return WorkerJobStatus_NOT_STARTED
}

func (m *WorkerJob) GetPeriod() *duration.Duration {
	if m != nil {
		return m.Period
	}
	return nil
}

func (m *WorkerJob) GetPrev() *timestamp.Timestamp {
	if m != nil {
		return m.Prev
	}
	return nil
}

func (m *WorkerJob) GetNext() *timestamp.Timestamp {
	if m != nil {
		return m.Next
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.WorkerJobStatus", WorkerJobStatus_name, WorkerJobStatus_value)
	proto.RegisterType((*Task)(nil), "proto.Task")
	proto.RegisterType((*WorkerJob)(nil), "proto.WorkerJob")
}

func init() { proto.RegisterFile("raker.proto", fileDescriptor_97affea0cdd5c5fb) }

var fileDescriptor_97affea0cdd5c5fb = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xd1, 0x4a, 0xfb, 0x30,
	0x14, 0xc6, 0xff, 0xdd, 0xbf, 0xad, 0xec, 0x14, 0xdc, 0xc8, 0x85, 0xc4, 0x5e, 0xb8, 0xb2, 0xab,
	0xe2, 0x45, 0x86, 0x9b, 0x2f, 0x20, 0x6c, 0x88, 0x5e, 0x6c, 0x92, 0x16, 0xbc, 0x1c, 0x29, 0x8b,
	0xa3, 0xd4, 0x36, 0x25, 0x49, 0x87, 0xaf, 0xe0, 0x5b, 0x4b, 0x4f, 0x5b, 0x2f, 0x26, 0xe8, 0x55,
	0x72, 0xf2, 0xfd, 0xbe, 0xef, 0xe4, 0x1c, 0x08, 0xb4, 0x28, 0xa4, 0x66, 0xb5, 0x56, 0x56, 0x11,
	0x0f, 0x8f, 0xf0, 0xe6, 0xa8, 0xd4, 0xf1, 0x5d, 0x2e, 0xb0, 0xca, 0x9a, 0xb7, 0xc5, 0xa1, 0xd1,
	0xc2, 0xe6, 0xaa, 0xea, 0xb0, 0x70, 0x76, 0xae, 0xdb, 0xbc, 0x94, 0xc6, 0x8a, 0xb2, 0xee, 0x80,
	0xf9, 0x3d, 0xb8, 0xa9, 0x30, 0x05, 0xa1, 0x70, 0x71, 0x92, 0xda, 0xe4, 0xaa, 0xa2, 0x4e, 0xe4,
	0xc4, 0x1e, 0x1f, 0x4a, 0x42, 0xc0, 0xad, 0x44, 0x29, 0xe9, 0x28, 0x72, 0xe2, 0x31, 0xc7, 0xfb,
	0xfc, 0x73, 0x04, 0xe3, 0x57, 0xa5, 0x0b, 0xa9, 0x9f, 0x55, 0xf6, 0x8b, 0x77, 0x06, 0xae, 0x15,
	0xa6, 0x40, 0x6f, 0xb0, 0x0c, 0xba, 0x9e, 0xac, 0x6d, 0xc8, 0x51, 0x20, 0x0c, 0x7c, 0x63, 0x85,
	0x6d, 0x0c, 0xfd, 0x1f, 0x39, 0xf1, 0xe5, 0xf2, 0xaa, 0x47, 0xbe, 0xc3, 0x13, 0x54, 0x79, 0x4f,
	0x91, 0x3b, 0xf0, 0x6b, 0xa9, 0x73, 0x75, 0xa0, 0x2e, 0x46, 0x5e, 0xb3, 0x6e, 0x40, 0x36, 0x0c,
	0xc8, 0xd6, 0xfd, 0x02, 0x78, 0x0f, 0x12, 0x06, 0x6e, 0xad, 0xe5, 0x89, 0x7a, 0x68, 0x08, 0x7f,
	0x18, 0xd2, 0x61, 0x23, 0x1c, 0xb9, 0x96, 0xaf, 0xe4, 0x87, 0xa5, 0xfe, 0xdf, 0x7c, 0xcb, 0xdd,
	0xae, 0x60, 0x72, 0xf6, 0x5b, 0x32, 0x81, 0x60, 0xbb, 0x4b, 0xf7, 0x49, 0xfa, 0xc0, 0xd3, 0xcd,
	0x7a, 0xfa, 0xaf, 0x7d, 0x78, 0xda, 0xee, 0x5f, 0xf8, 0xee, 0x91, 0x6f, 0x92, 0x64, 0xea, 0x64,
	0x3e, 0xc6, 0xad, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x99, 0x8c, 0xbb, 0x5c, 0xd4, 0x01, 0x00,
	0x00,
}
